[workspace]
members = ["."]

[package]
name = "yaql"
version = "0.1.0"
edition = "2021"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.12"

[dependencies]
lalrpop-util = { version = "0.19.12", features = ["lexer"] }
regex = "1"
serde_json = "1.0.91"
